{
 "title": "Ontario",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# Under Construction!! \n\nData may be wrong, graphs may be wrong. Work in progress, Feb 2024"
   }
  },
  {
   "title": "Carbon Intensity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gCO₂eq/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"carbon_intensity\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ontario_carbon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carbon\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |>mean()\r\n  |>group()"
    }
   ]
  },
  {
   "title": "Peak Demand",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MW" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"onpower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"demand\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mw\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\r\nfrom(bucket: \"onpower\")\r\n  |> range(start: -24h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputmw\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> group(columns: [\"generator\", \"type\"], mode:\"by\")  \r\n  |> mean()\r\n  |> group(columns: [\"type\"], mode:\"by\")  \r\n  |> sum(column: \"_value\")  \r\n  |> map(fn: (r) => ({ r with _value: math.round(x: r._value) }))  \r\n  |>group()"
    }
   ]
  },
  {
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "import \"math\"\r\nfrom(bucket: \"onpower\")\r\n  |> range(start: -24h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputmw\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> group(columns: [\"generator\", \"type\"], mode:\"by\")  \r\n  |> mean()\r\n  |> group(columns: [\"type\"], mode:\"by\")  \r\n  |> sum(column: \"_value\")  \r\n  |> map(fn: (r) => ({ r with _value: math.round(x: r._value) }))  \r\n  |> map(fn: (r) => ({ r with _pivot: \"pivot\" }))  \r\n  |> pivot(rowKey:[\"_pivot\"], columnKey: [\"type\"], valueColumn: \"_value\")  \r\n  |> drop(columns: [\"_pivot\"])  \r\n // |>group()"
    },
    {
     "query": "import \"math\"\r\ndata = from(bucket: \"onpower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputmw\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> group(columns: [\"_time\", \"type\"], mode:\"by\")  \r\n  |> sum(column: \"_value\")  \r\n  |> map(fn: (r) => ({ r with _value: math.round(x: r._value) }))  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"type\"], valueColumn: \"_value\")  \r\n  //|> drop(columns: [\"_time\"])  \r\n  |> map(fn: (r) => ({ r with _value: 0.0 }))  \r\n  |>group()\r\n\r\nn_records = (data\r\n  |> count()\r\n  |> findRecord(\r\n    fn: (key) => true,\r\n    idx: 0,\r\n    ))._value\r\n\r\ndata |> limit(n: n_records-1)\r\n  |> drop(columns: [\"_value\", \"_time\"])"
    },
    {
     "query": "from(bucket: \"onpower\")\r\n  |> range(start: -90d, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacitymw\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> max()  \r\n  |> group(columns: [\"type\"], mode:\"by\")  \r\n  |> sum(column: \"_value\")  \r\n  |>group()\r\n  |> map(fn: (r) => ({ r with _pivot: \"pivot\" }))  \r\n  |> pivot(rowKey:[\"_pivot\"], columnKey: [\"type\"], valueColumn: \"_value\")  \r\n  |> drop(columns: [\"_pivot\"])  "
    }
   ]
  },
  {
   "title": "Ontario Grid Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"onpower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputmw\" )\r\n  //|> filter(fn: (r) => r[\"type\"] == \"NUCLEAR\" or r[\"type\"] == \"WIND\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"_time\", \"_field\", \"type\"], mode:\"by\")\r\n  |> sum(column: \"_value\")\r\n  |> group(columns: [\"_field\", \"type\"], mode:\"by\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"type\"], valueColumn: \"_value\")  "
    }
   ]
  },
  {
   "title": "Ontario Grid Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"onpower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"production\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputmw\" )\r\n  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with type_loc: r.type + \"_\" + r.generator }))\r\n  |> group(columns: [\"_time\", \"_field\", \"type_loc\"], mode:\"by\")\r\n  |> mean(column: \"_value\")\r\n  |> group(columns: [\"_field\", \"type_loc\"], mode:\"by\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"type_loc\"], valueColumn: \"_value\")  "
    }
   ]
  }
 ]
}